# Generated by Django 6.0.5 on 2026-05-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pets',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('shelter', 'Shelter'), ('lost', 'Lost/Found')], default='shelter', max_length=20),
        ),
    ]
