# Generated by Django 5.1.5 on 2026-05-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_remove_pet_pet_type_pet_pet_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.user'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_status',
            field=models.CharField(choices=[('shelter', 'Shelter'), ('lost', 'Lost'), ('found', 'Found')], max_length=20),
        ),
    ]
